dist: trusty  # 2014 Ubuntu, whoooo!
sudo: required  # Necesary for installing LaTeX packages

language: python
python: "3.5"

install:
    - sudo apt-get update -qq  # No dependencies?
    - pip install mypy

script:
    - mypy --package whitewater


after_success:  # Build binaries and documentation
    - cd docs  # Time to do documentation
    - sudo apt-get install -y --no-install-recommends pandoc pandoc-citeproc texlive-base texlive-latex-base texlive-generic-recommended texlive-fonts-recommended texlive-fonts-extra texlive-extra-utils texlive-latex-recommended texlive-latex-extra texlive-xetex lmodern pgf texlive-science
    - make travis
    - cd ..

# Run tests on master & dev
branches:
    only:
        - master
        - dev

# Only deploy on master
deploy:
    provider: releases
    api_key: "$GH_TOKEN"
    file: docs/whitewater.pdf
    skip_cleanup: true
    overwrite: true
    prerelease: true
    on:
        branch:
            - master

notifications:
    email: false  # Stop bothering me

